# **Pandas ASSIGNMENT**

**Create a dataframe with the following columns: name, age, and gender. The
dataframe
should have 10 rows of data. (Score: 2)**

In [ ]:
import pandas as pd
data = {"name": ["Sarath", "Sona", "Diya", "Ronaldo", "Messi", "Dulqer", "Tovino", "Aliabhatt", "Kiara", "Rashmika"],
        "age": [18, 25, 16, 41, 38, 42, 36, 34, 30, 28],
        "gender": ["M", "F", "F", "M", "M", "M", "M", "F", "F", "F"]}
df = pd.DataFrame(data)
df

        name  age gender
0     Sarath   18      M
1       Sona   25      F
2       Diya   16      F
3    Ronaldo   41      M
4      Messi   38      M
5     Dulqer   42      M
6     Tovino   36      M
7  Aliabhatt   34      F
8      Kiara   30      F
9   Rashmika   28      F

**Add a new column to the data frame created in question 1, called occupation.
The values for this column should be Programmer, Manager, and Analyst,
corresponding to the rows in the dataframe. (Score: 1)**

In [ ]:
occupations = ["Programmer", "Manager", "Analyst", "Programmer", "Manager",
               "Analyst", "Programmer", "Manager", "Analyst", "Programmer"]
df["occupation"] = occupations
df

        name  age gender  occupation
0     Sarath   18      M  Programmer
1       Sona   25      F     Manager
2       Diya   16      F     Analyst
3    Ronaldo   41      M  Programmer
4      Messi   38      M     Manager
5     Dulqer   42      M     Analyst
6     Tovino   36      M  Programmer
7  Aliabhatt   34      F     Manager
8      Kiara   30      F     Analyst
9   Rashmika   28      F  Programmer

**Select the rows of the dataframe where the age is greater than or equal to 30.
(Score: 1)**

In [ ]:
age = df[df["age"]>=30]
age

        name  age gender  occupation
3    Ronaldo   41      M  Programmer
4      Messi   38      M     Manager
5     Dulqer   42      M     Analyst
6     Tovino   36      M  Programmer
7  Aliabhatt   34      F     Manager
8      Kiara   30      F     Analyst

**Convert this dataframe to a CSV file and read that CSV file, and finally display
the contents. (Score: 1)**

In [ ]:
df.to_csv("Persons_data.csv", index=False)
print("CSV file created")
df_csv = pd.read_csv("Persons_data.csv")
df_csv

CSV file created

        name  age gender  occupation
0     Sarath   18      M  Programmer
1       Sona   25      F     Manager
2       Diya   16      F     Analyst
3    Ronaldo   41      M  Programmer
4      Messi   38      M     Manager
5     Dulqer   42      M     Analyst
6     Tovino   36      M  Programmer
7  Aliabhatt   34      F     Manager
8      Kiara   30      F     Analyst
9   Rashmika   28      F  Programmer